### PR TITLE
Trying to make the instructions clearer in the Private Repo pages

### PR DESCRIPTION
**Pull request by mattmorton**
I've mad a couple of changes which I hope will improve the instructions of creating and using a Private Repo to newcomers.

### CODE REVIEW

**Comment by mattmorton** [comment]
Linked to Issue https://github.com/CocoaPods/guides.cocoapods.org/issues/69

**Comment by orta** [comment]
I like this, if you can think of a place to add an example, here is a

* [Podfile](https://github.com/artsy/eigen/blob/master/Podfile)
* [Specs Repo](https://github.com/artsy/Specs) 

That can be given as examples? Otherwise I'll merge.

**Comment by mattmorton** [comment]
Cool, an example would help.  I'll take a look.

**Comment by mattmorton** [comment]
I've added an example.

**Comment by orta** [comment]
Brilliant @mattmorton !

**Pull request merged**
