### PR TITLE
Use gems from the Gemfile rather than submodules

### PR DESCRIPTION
**Pull request by segiddins**
This way, we're not manually mangling load paths and updating submodules.  (It will now also use CLAide to ensure all the default plugins are required)

\c @mtitolo @orta

### CODE REVIEW

**Comment by orta** [comment]
bravo.

**Comment by mtitolo** [comment]
:tada:

**Comment by orta** [comment]
Yep, this looks good. Merging :+1:

**Comment by segiddins** [comment]
And merging it didn't even break anything!

**Pull request merged**
