### PR TITLE
Update CONTRIBUTING

### PR DESCRIPTION
**Pull request by AliSoftware**
Adding info for the auto-generated Podfile & Podspec syntax pages

### CODE REVIEW

**Comment by AliSoftware** [comment]
Fixed typo (thx @floere)

**Comment by orta** [comment]
Also the commands section: https://guides.cocoapods.org/terminal/commands.html

Basically anything in "Reference" comes from Core

**Comment by AliSoftware** [comment]
Good point. Fixed.

**Comment by orta** [comment]
commands are not generated from commits, but from the command objects themselves I believe

**Comment by AliSoftware** [comment]
Just realized that I forgot to mention the URL for those Command Line APIs 😉
 
@orta indeed [this page about "pod init"](https://guides.cocoapods.org/terminal/commands.html#pod_init) is generated from [those comments](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/command/init.rb#L9-L17) and the `Pod::Command#arguments`.
But do you know how [this page](https://guides.cocoapods.org/terminal/commands.html#group_installation) is generated then?

**Comment by orta** [comment]
https://github.com/CocoaPods/guides.cocoapods.org/blob/master/source/templates/commands.html.slim#L26-L44

ideally that could move to its own md files

**Comment by AliSoftware** [comment]
Better?

**Comment by orta** [comment]
Yes

**Comment by orta** [comment]
good show sir

**Comment by AliSoftware** [comment]
:bowtie:

**Pull request merged**
