### PR TITLE
pod install vs update - review

### PR DESCRIPTION
**Pull request by AliSoftware**
This is the follow-up of #101 to address late feedback after initial merge. \cc @orta @kylef

### CODE REVIEW

**Comment by kylef** [comment]
Perfect, much better. Thanks for addressing :ok_hand:

**Comment by AliSoftware** [comment]
Wait, what, already merged?! I haven't addressed them all yet :smile:

**Comment by AliSoftware** [comment]
Especially still pending:

* https://github.com/CocoaPods/guides.cocoapods.org/pull/101#discussion_r48984337
* https://github.com/CocoaPods/guides.cocoapods.org/pull/101#discussion_r48985489

**Comment by kylef** [comment]
@AliSoftware I wasn't sure if you wanted to change everything (I was merely suggesting). Maybe should mention if a PR isn't ready for merge in future.

**Comment by AliSoftware** [comment]
Yeah sorry I should have used `[WIP]` here (only used to us this tag for code PRs)

**Pull request merged**
