### PR TITLE
typo: XML_Fromatter → XML_Formatter

### PR DESCRIPTION
**Pull request by Coeur**
I am not sure how this file is used or generated.
But it feels like a typo similar to https://github.com/CocoaPods/Xcodeproj/commit/d714b6d00f4e19676e128262461993be51c612c8

### CODE REVIEW

**Comment by Coeur** [comment]
@orta you need to tap "Load diff", then search for XML_Fromatter or XML_Formatter

**Comment by dnkoutso** [comment]
Side by side also shows up but its difficult to compare anyway

**Comment by Coeur** [comment]
Note that I feel that we may be able to directly delete the file, as it seems like an old artefact from Twitter Bootstrap 2's Typeahead.

If we're still using the file, we need to look how to maintain it, where is the generator for it.

**Comment by orta** [comment]
Yeah, I can't think of where this would be used, there's no search on the guides. Probably an artifact of porting the site, I'm fine with removing it instead

**Comment by Coeur** [comment]
@orta I'll let you handle the deletion. :)

**Pull request closed without merging**
