### PR TITLE
[YARD] Use custom tag for CocoaPods Availability

### PR DESCRIPTION
**Pull request by nwest**
Works like a charm. See: https://github.com/CocoaPods/cocoapods-deintegrate/pull/23.

screen shot 2016-05-04 at 11 10 05 am

### CODE REVIEW

**Comment by segiddins** [comment]
👍🏻

**Comment by k0nserv** [comment]
Could we give the availability notations some more custom style? I'll leave it up to @orta, but maybe something with a lower contrast color

**Comment by orta** [comment]
Aye, let's get it in, I want to do a polish pass on the guides at some point soon anyway 👍

**Comment by nwest** [comment]
I'll start patching the Commands so they show up in the next release(s). 💃

**Pull request merged**
